### ISSUE TITLE
Failed to load map

### ISSUE THREAD

**Issue by tprochazka** [tigershan1130/UE5-active-ragdoll-with-floating-capsule#1]
There is just missing test map file, it fails with this error

```
Failed to load map!
../../../../../../Users/tomas/Documents/Unreal Projects/Active-ragdoll-with-floating-capsule/Content/Designer/LevelPrototyping/Map000/TestMap.umap appears to be an asset file.
```

**Comment by tprochazka** [comment]
But file `TestMap.umap` itself is there, weird, UE Editor didn't see it.

**Comment by tprochazka** [comment]
Sorry, this is my mistake. I forgot about `GIT LFS`

**Comment by tprochazka** [comment]
But it anyway works weirdly, at least in UE 5.1.1

**Comment by tigershan1130** [comment]
> But it anyway works weirdly, at least in UE 5.1.1

The reason is that there is no actual balancing and walking script for this, simply a capsule. You might want to adjust the movement script and switch a model with shorter limbs to minimize the "weirdly" physics issue.
